"""addresses, admin users, order status history, cancel reasons

Revision ID: 04687c619c59
Revises: 716aedda2617
Create Date: 2026-09-04 08:13:14.498345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '04687c619c59'
down_revision: Union[str, Sequence[str], None] = '716aedda2617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Тип orderstatus в Postgres уже создан миграцией 716aedda2617 (для
# orders.status) — здесь ссылаемся на него по имени с create_type=False,
# иначе SQLAlchemy попытается выполнить CREATE TYPE ещё раз и упадёт с
# DuplicateObject (enum не привязан к конкретной колонке, это тип на уровне БД).
order_status_enum = postgresql.ENUM(
    'NEW', 'PAID', 'ASSEMBLED', 'SHIPPED', 'DELIVERED', 'CANCELLED',
    name='orderstatus', create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', order_status_enum, nullable=True),
    sa.Column('to_status', order_status_enum, nullable=False),
    sa.Column('changed_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    op.add_column('subscriptions', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'cancel_reason')
    op.drop_column('subscriptions', 'address_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'address_id')
    op.drop_table('order_status_history')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
