"""make blank-default text columns not null

Revision ID: bd9f184b7337
Revises: 126e24005316
Create Date: 2026-09-04 08:25:29.915249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9f184b7337'
down_revision: Union[str, Sequence[str], None] = '126e24005316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Сначала подчистить NULL, которые могли образоваться до этой миграции:
    # SQLAdmin превращал пустую строку в форме в NULL для nullable-колонок
    # (см. sqladmin/_queries.py:_set_attributes_sync) — без этого шага
    # ALTER COLUMN ... NOT NULL ниже упадёт на существующих данных.
    _blank_default_columns = [
        ("addresses", "label"),
        ("admin_users", "full_name"),
        ("customers", "full_name"),
        ("customers", "contact"),
        ("delivery_methods", "description"),
        ("order_status_history", "changed_by"),
        ("order_status_history", "note"),
        ("orders", "customer_name"),
        ("orders", "customer_contact"),
        ("orders", "delivery_address"),
        ("orders", "tracking_number"),
        ("orders", "cancel_reason"),
        ("payment_transactions", "provider_payment_id"),
        ("payment_transactions", "note"),
        ("products", "description"),
        ("products", "cover_url"),
        ("stock_movements", "note"),
        ("stock_movements", "changed_by"),
        ("subscriptions", "delivery_address"),
        ("subscriptions", "cancel_reason"),
    ]
    for table, column in _blank_default_columns:
        op.execute(f"UPDATE {table} SET {column} = '' WHERE {column} IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'label',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('admin_users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('delivery_methods', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('order_status_history', 'changed_by',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('order_status_history', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'customer_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'tracking_number',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('orders', 'cancel_reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('payment_transactions', 'provider_payment_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('payment_transactions', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'cover_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('stock_movements', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('stock_movements', 'changed_by',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('subscriptions', 'delivery_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('subscriptions', 'cancel_reason',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'cancel_reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('subscriptions', 'delivery_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('stock_movements', 'changed_by',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('stock_movements', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'cover_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('payment_transactions', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('payment_transactions', 'provider_payment_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('orders', 'cancel_reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('orders', 'tracking_number',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('orders', 'customer_contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('order_status_history', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('order_status_history', 'changed_by',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('delivery_methods', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('customers', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('admin_users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('addresses', 'label',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
